input_parameters:
  centroid: [600.0, 0.0, 80.0]
  radius: 350.0
  height: 105.0
  inclination: 30.0
  resolution: 200
  speed: 40.0
  start_position: -179
  end_position: 0

initial_joint_positions: [0, 0, 30, 0, 60, 180]
