input_parameters:
  centroid: [500.0, 0.0, 0.0]
  radius: 200.0
  height: 20.0
  inclination: 30.0
  resolution: 100
  speed: 20.0
  start_position: 0
  end_position: 360

initial_joint_positions: [0, 60.86, -1.18, 0, 30.32, 0]
